import { AppBar, Grid, IconButton, Typography } from '@mui/material'
import { Metadata } from 'next'

export const metadata: Metadata = {
    title: {
        default: 'NextJs Learning | Codevulation',
        template: '%s | Codevalution'
    },
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
  children: React.ReactNode
}) {
    return (
        <html lang="en">
            <Grid
                container
                component='body'
                gap={1}
            >
                <AppBar
                    position="static"
                    sx={{
                        px: '1rem',
                        py: '0.5rem',
                    }}
                >
                    <Typography variant="h6">
            			Next.js Learning
                    </Typography>
                </AppBar>
                {children}
                <AppBar
                    color="success"
                    position="static"
                    sx={{
                        px: '1rem',
                        py: '0.5rem',
                    }}
                >
                    <Typography variant="h6">
            Next.js Learning
                    </Typography>
                </AppBar>
            </Grid>
        </html>
    )
}
